-- MySQL Script generated by MySQL Workbench
-- gaa 05 okt 2019 13:55:10 GMT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema GRH
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema GRH
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `GRH` DEFAULT CHARACTER SET utf8 ;
USE `GRH` ;

-- -----------------------------------------------------
-- Table `GRH`.`Patient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GRH`.`Patient` (
  `idPatient` INT NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(45) NULL,
  `Prenom` VARCHAR(45) NULL,
  `Date_Nais` DATE NULL,
  PRIMARY KEY (`idPatient`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `GRH`.`Service`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GRH`.`Service` (
  `idService` INT NOT NULL,
  `Nom` VARCHAR(45) NULL,
  PRIMARY KEY (`idService`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `GRH`.`Specialite`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GRH`.`Specialite` (
  `idSecialite` INT NOT NULL,
  `Nom` VARCHAR(45) NULL,
  `Service_idService` INT NOT NULL,
  PRIMARY KEY (`idSecialite`),
  CONSTRAINT `fk_Specialite_Service`
    FOREIGN KEY (`Service_idService`)
    REFERENCES `GRH`.`Service` (`idService`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_Specialite_Service_idx` ON `GRH`.`Specialite` (`Service_idService` ASC);


-- -----------------------------------------------------
-- Table `GRH`.`Medecin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GRH`.`Medecin` (
  `idMedecin` INT NOT NULL,
  `Prenom_Med` VARCHAR(45) NULL,
  `Email_Med` VARCHAR(45) NULL,
  `Tel_Med` INT NULL,
  `Pseudo` VARCHAR(45) NULL,
  `MDP` VARCHAR(45) NULL,
  `Service_idService` INT NOT NULL,
  `Specialite_idSecialite` INT NOT NULL,
  PRIMARY KEY (`idMedecin`),
  CONSTRAINT `fk_Medecin_Service1`
    FOREIGN KEY (`Service_idService`)
    REFERENCES `GRH`.`Service` (`idService`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Medecin_Specialite1`
    FOREIGN KEY (`Specialite_idSecialite`)
    REFERENCES `GRH`.`Specialite` (`idSecialite`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_Medecin_Service1_idx` ON `GRH`.`Medecin` (`Service_idService` ASC);

CREATE INDEX `fk_Medecin_Specialite1_idx` ON `GRH`.`Medecin` (`Specialite_idSecialite` ASC);


-- -----------------------------------------------------
-- Table `GRH`.`Secretaire`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GRH`.`Secretaire` (
  `idSec` INT NOT NULL,
  `Nom` VARCHAR(45) NULL,
  `Prenom` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NULL,
  `Tel` VARCHAR(45) NULL,
  `Pseudo` VARCHAR(45) NULL,
  `MDP` VARCHAR(45) NULL,
  PRIMARY KEY (`idSec`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `GRH`.`RDV`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GRH`.`RDV` (
  `idRDV` INT NOT NULL,
  `Date_RDV` VARCHAR(45) NULL,
  `Heure_Deb` VARCHAR(45) NULL,
  `Heure_Fin` VARCHAR(45) NULL,
  `Medecin_idMedecin` INT NOT NULL,
  `Patient_idPatient` INT NOT NULL,
  `Secretaire_idSec` INT NOT NULL,
  PRIMARY KEY (`idRDV`),
  CONSTRAINT `fk_RDV_Medecin1`
    FOREIGN KEY (`Medecin_idMedecin`)
    REFERENCES `GRH`.`Medecin` (`idMedecin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RDV_Patient1`
    FOREIGN KEY (`Patient_idPatient`)
    REFERENCES `GRH`.`Patient` (`idPatient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RDV_Secretaire1`
    FOREIGN KEY (`Secretaire_idSec`)
    REFERENCES `GRH`.`Secretaire` (`idSec`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_RDV_Medecin1_idx` ON `GRH`.`RDV` (`Medecin_idMedecin` ASC);

CREATE INDEX `fk_RDV_Patient1_idx` ON `GRH`.`RDV` (`Patient_idPatient` ASC);

CREATE INDEX `fk_RDV_Secretaire1_idx` ON `GRH`.`RDV` (`Secretaire_idSec` ASC);


-- -----------------------------------------------------
-- Table `GRH`.`Plage_horaire`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GRH`.`Plage_horaire` (
  `id_Plage` INT NOT NULL,
  `Date` VARCHAR(45) NULL,
  `Heure_Deb` VARCHAR(45) NULL,
  `Heure_Fin` VARCHAR(45) NULL,
  `RDV_idRDV` INT NOT NULL,
  PRIMARY KEY (`id_Plage`),
  CONSTRAINT `fk_Plage_horaire_RDV1`
    FOREIGN KEY (`RDV_idRDV`)
    REFERENCES `GRH`.`RDV` (`idRDV`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_Plage_horaire_RDV1_idx` ON `GRH`.`Plage_horaire` (`RDV_idRDV` ASC);


-- -----------------------------------------------------
-- Table `GRH`.`Medecin_Plage_horaire`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GRH`.`Medecin_Plage_horaire` (
  `Medecin_idMedecin` INT NOT NULL,
  `Plage_horaire_id_Plage` INT NOT NULL,
  PRIMARY KEY (`Medecin_idMedecin`, `Plage_horaire_id_Plage`),
  CONSTRAINT `fk_Medecin_has_Plage_horaire_Medecin1`
    FOREIGN KEY (`Medecin_idMedecin`)
    REFERENCES `GRH`.`Medecin` (`idMedecin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Medecin_has_Plage_horaire_Plage_horaire1`
    FOREIGN KEY (`Plage_horaire_id_Plage`)
    REFERENCES `GRH`.`Plage_horaire` (`id_Plage`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_Medecin_has_Plage_horaire_Plage_horaire1_idx` ON `GRH`.`Medecin_Plage_horaire` (`Plage_horaire_id_Plage` ASC);

CREATE INDEX `fk_Medecin_has_Plage_horaire_Medecin1_idx` ON `GRH`.`Medecin_Plage_horaire` (`Medecin_idMedecin` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
